export enum ActionType {
  ACTION1 = "action1",
  ACTION2 = "action2",
  GETMUSICTYPES = "GET_MUSIC_TYPE",
  PLAYING = "PLAYING_SONG",
  NEXTANDPRE = "NEXTANDPRE_SONG",
  FIRSTMUSIC = "FIRSTMUSIC",
}
